variables:
  SERVICE_NAME: "oebl-research-fronted"

stages:
  - build
  # - test
  - push
  - deploy

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-stage:
  stage: build
  script:
    - docker build --build-arg ENV_FILE=env-stage.env -t $CI_REGISTRY/${SERVICE_NAME}:$CI_BUILD_REF .
  only:
    - dev

build-master:
  stage: build
  script:
    - docker build --build-arg ENV_FILE=env-production.env -t $CI_REGISTRY/${SERVICE_NAME}:$CI_BUILD_REF .
  only:
    - master

build-test:
  stage: build
  script:
    - docker build --build-arg ENV_FILE=env-test.env -t $CI_REGISTRY/${SERVICE_NAME}:$CI_BUILD_REF .
  except:
    - dev
    - master

# test:
#  stage: test
#  script:
#    - docker run --env-file=env-test.env ${DOCKER_REGISTRY}/${SERVICE_NAME}:${CI_BUILD_REF} test

push:
  stage: push
  script:
    - docker push $CI_REGISTRY/${SERVICE_NAME}:CI_BUILD_REF
  only:
    # - dev
    - master
