name: deploy frontent
on:
  push:
  workflow_dispatch:

jobs:
  setup_workflow_env:
    runs-on: ubuntu-latest
    outputs:
      image_tagged: apis-oebl-irs-frontend
      registry_root: ghcr.io/${{ github.repository }}/
      default_port: "3333"
      APP_NAME: frontend2
      APP_ROOT: "/"
      SERVICE_ID: "18549"
      PUBLIC_URL: https://oebl-research.acdh-dev.oeaw.ac.at
      POSTGRES_ENABLED: "false"
    steps:
      - run: "/bin/true"      

  build_and_push_to_registry:
    runs-on: ubuntu-latest
    needs: [setup_workflow_env]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ needs.setup_workflow_env.outputs.registry_root }}${{ needs.setup_workflow_env.outputs.image_tagged }}/${{ github.ref_name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest
            type=raw,value={{sha}}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          push: true
  
  deploy:
    needs: [setup_workflow_env, build_and_push_to_registry]
    uses: acdh-oeaw/gl-autodevops-minimal-port/.github/workflows/deploy-cluster-2.yml@main
    secrets: inherit
    with:
      DOCKER_TAG: ${{ needs.setup_workflow_env.outputs.registry_root }}${{ needs.setup_workflow_env.outputs.image_tagged }}/${{ github.ref_name }}
      APP_NAME: ${{ needs.setup_workflow_env.outputs.APP_NAME }}
      APP_ROOT: ${{ needs.setup_workflow_env.outputs.APP_ROOT }}
      SERVICE_ID: ${{ needs.setup_workflow_env.outputs.SERVICE_ID }}
      PUBLIC_URL: ${{ needs.setup_workflow_env.outputs.PUBLIC_URL }}
      POSTGRES_ENABLED: ${{ needs.setup_workflow_env.outputs.POSTGRES_ENABLED == 'true'}}
      environment: "${{ needs.setup_workflow_env.outputs.environment}}"
      default_port: "${{ needs.setup_workflow_env.outputs.default_port}}"
