name: Validate

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - development
      - main
  push:
    branches:
      - development
      - main
  workflow_dispatch:

jobs:
  validate:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Format
        run: npm run format:check

      - name: Lint
        run: npm run lint:check

      - name: Typecheck
        run: npm run types:check

      - name: Test
        run: npm run test

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Build app
        run: npm run build
        env:
          VUE_APP_API_HOST: "https://oebl-irs-backend.acdh-dev.oeaw.ac.at"
          VUE_APP_EVENTBUS_HOST: "http://localhost:3333"
          VUE_APP_WEBAPP_HOST: "http://localhost:3333"

      - name: Run e2e tests
        run: npm run test:e2e
        env:
          SERVICE_SECRET: "${{ secrets.K8S_SECRET_SERVICE_SECRET }}"
          ALLOWED_ORIGIN: '["http://localhost:3333"]'
          ZOTERO_USER: "${{secrets.K8S_SECRET_ZOTERO_USER }}"
          ZOTERO_API_KEY: "${{secrets.K8S_SECRET_ZOTERO_API_KEY }}"

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
